name: local_auth_example
description: Demonstrates how to use the local_auth plugin.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_auth_invisible:
    path: ../

flutter:
  uses-material-design: true
