name: flutter_local_auth_invisible
description: Flutter plugin for Android and iOS device authentication sensors
  such as Fingerprint Reader and Touch ID with no visible dialog on Android.
homepage: https://github.com/priezz/flutter_local_auth_invisible
version: 0.5.0

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  intl: ^0.19.0
  platform: ^3.1.4
